#include "game/Stage4Game.h"
#include "rendering/AssetManager.h"
#include "rendering/BossSprite.h"
#include "rendering/Backdrop.h"
#include "ui/GameHUD.h"
#include "raylib.h"
#include <algorithm>
#include <cmath>

namespace district_fury {
namespace {
constexpr float kStageEnd = 5600.0f;
constexpr float kPi = 3.14159265359f;
float Dist(Vector3D a, Vector3D b){const float dx=a.x-b.x,dy=a.y-b.y;return std::sqrt(dx*dx+dy*dy);}
Color Alpha(Color c,float a){c.a=(unsigned char)(std::clamp(a,0.0f,1.0f)*255);return c;}
struct Spawn{float x,y;StreetEnemyType type;};
// DF-013.2: seguridad de Kessler — reutiliza los tipos ya implementados
// (Enforcer/ArmoredGuard/UrbanNinja/ChemicalSoldier), sin Punk/Charger de
// calle: la torre corporativa usa guardias de elite, no pandillas.
const Spawn waves[][4]={
 {{760,570,StreetEnemyType::Enforcer},{940,530,StreetEnemyType::UrbanNinja},{1120,610,StreetEnemyType::Enforcer},{0,0,StreetEnemyType::Enforcer}},
 {{1560,560,StreetEnemyType::ArmoredGuard},{1740,610,StreetEnemyType::ChemicalSoldier},{1920,530,StreetEnemyType::ArmoredGuard},{0,0,StreetEnemyType::Enforcer}},
 {{2400,610,StreetEnemyType::UrbanNinja},{2580,540,StreetEnemyType::UrbanNinja},{2760,590,StreetEnemyType::ArmoredGuard},{2940,525,StreetEnemyType::Enforcer}},
 {{3500,560,StreetEnemyType::ArmoredGuard},{3680,615,StreetEnemyType::Enforcer},{3860,530,StreetEnemyType::UrbanNinja},{4040,590,StreetEnemyType::ChemicalSoldier}}
};
}
Stage4Game::Stage4Game()=default;
void Stage4Game::Init(){player.Reset();enemies.clear();projectiles.clear();particles.clear();combatWorld.Reset();flow=Flow::Intro;stageTime=0;combo=0;maxCombo=0;damageTaken=0;defeated=0;wave=0;arenaLocked=false;bannerTimer=1.8f;cameraX=640;boss=TitanXImproved{};kessler=KesslerCameo{};BuildStage();}
void Stage4Game::BuildStage(){for(int w=0;w<4;++w)for(const auto&s:waves[w])if(s.x>0){StreetEnemy e;e.Init({s.x,s.y,0},s.type);enemies.push_back(e);}boss=TitanXImproved{};}
void Stage4Game::SpawnWave(int id){wave=id;arenaLocked=true;bannerTimer=1.35f;for(auto&e:enemies)e.active=false;const float lo=id==1?600:id==2?1350:id==3?2200:3300;const float hi=id==1?1400:id==2?2200:id==3?3300:4400;for(auto&e:enemies)if(e.position.x>=lo&&e.position.x<hi)e.Activate();}
void Stage4Game::SpawnImpact(Vector3D pos,Color color,bool heavy){const int n=heavy?30:16;for(int i=0;i<n;++i){float a=(float)i/n*2*kPi;float s=(float)GetRandomValue(85,heavy?380:240);particles.push_back({pos,{std::cos(a)*s,std::sin(a)*s},heavy?.52f:.3f,heavy?.52f:.3f,(float)GetRandomValue(3,heavy?10:6),color});}}
void Stage4Game::SpawnEnergy(){float d=player.facing==Facing::Right?1.f:-1.f;projectiles.push_back({{player.position.x+d*72,player.position.y-72,0},d*760,.9f,player.isRageMode?32:23,true,false});SpawnImpact({player.position.x+d*55,player.position.y-72,0},{40,210,255,255},true);}
void Stage4Game::UpdateProjectiles(float dt){for(auto&p:projectiles){if(!p.active)continue;p.pos.x+=p.vx*dt;p.life-=dt;if(p.life<=0){p.active=false;continue;}CombatBox b{p.pos.x-18,p.pos.y-18,36,36};if(!p.fromBoss){for(auto&e:enemies)if(e.active&&!e.IsDefeated()&&b.Intersects(e.GetHurtbox())){e.TakeDamage(p.damage,{p.vx>0?420.f:-420.f,0,0});p.active=false;++combo;comboTimer=1;maxCombo=std::max(maxCombo,combo);SpawnImpact(p.pos,{50,215,255,255},true);hitstop=.1f;shake=.12f;break;}if(flow==Flow::Boss&&!boss.defeated&&p.active){CombatBox bb{boss.pos.x-85,boss.pos.y-165,170,165};if(b.Intersects(bb)&&boss.invuln<=0){boss.hp=std::max(0,boss.hp-p.damage);boss.invuln=.12f;p.active=false;++combo;comboTimer=1;maxCombo=std::max(maxCombo,combo);SpawnImpact(p.pos,{50,215,255,255},true);hitstop=.12f;shake=.16f;}}}else if(p.active&&player.state!=PlayerState::Defeat&&player.dashInvulnerability<=0.0f&&b.Intersects(player.GetHurtbox())){int before=player.hp;player.TakeDamage(p.damage);damageTaken+=before-player.hp;combo=0;comboTimer=0;p.active=false;SpawnImpact(player.position,{125,235,95,255},true);hitstop=.09f;shake=.14f;}}projectiles.erase(std::remove_if(projectiles.begin(),projectiles.end(),[](const Projectile&p){return !p.active;}),projectiles.end());}
void Stage4Game::HandlePlayerHits(){if(!player.AttackIsActive()||player.hasHit||player.attackType==AttackType::Energy)return;CombatBox hit=player.GetAttackHitbox();int best=-1;float near=1e9f;for(size_t i=0;i<enemies.size();++i)if(enemies[i].active&&!enemies[i].IsDefeated()&&hit.Intersects(enemies[i].GetHurtbox())){float d=Dist(player.position,enemies[i].position);if(d<near){near=d;best=(int)i;}}if(best<0)return;auto&e=enemies[(size_t)best];int dmg=player.GetAttackDamage()+(player.isRageMode?5:0);float dir=player.facing==Facing::Right?1.f:-1.f;e.TakeDamage(dmg,{dir*player.GetAttackKnockback(),0,0});player.hasHit=true;++combo;comboTimer=1;maxCombo=std::max(maxCombo,combo);SpawnImpact(e.position,player.attackType==AttackType::Kick?Color{255,150,45,255}:Color{255,235,150,255},player.attackType==AttackType::Kick);hitstop=.08f;shake=.1f;}
void Stage4Game::HandleEnemyHits(){if(player.state==PlayerState::Defeat)return;for(auto&e:enemies)if(e.active&&!e.IsDefeated()&&!e.hasHit&&e.AttackIsActive()&&e.GetAttackHitbox().Intersects(player.GetHurtbox())){int before=player.hp;player.TakeDamage((int)e.attackDamage);damageTaken+=before-player.hp;e.hasHit=true;combo=0;comboTimer=0;SpawnImpact(player.position,{125,235,95,255},false);hitstop=.085f;shake=.12f;break;}}
void Stage4Game::EnterBoss(){arenaLocked=true;boss=TitanXImproved{};boss.pos={5080,575,0};boss.attackTimer=1.0f;flow=Flow::BossIntro;bannerTimer=2.6f;kessler.Start(boss.pos.x+520,boss.pos.x+170,boss.pos.x+760,boss.pos.y-40,{"Titan-X ya no es un prototipo, Rayden.","El suero X por fin encontro un cuerpo digno.","Diviertete. Yo tengo un clon que terminar."});}
void Stage4Game::HandleBossHits(){if(flow!=Flow::Boss||boss.defeated||boss.invuln>0||!player.AttackIsActive()||player.hasHit||player.attackType==AttackType::Energy)return;if(player.GetAttackHitbox().Intersects({boss.pos.x-85,boss.pos.y-165,170,165})){int dmg=player.GetAttackDamage()+(player.isRageMode?8:0);boss.hp=std::max(0,boss.hp-dmg);boss.invuln=.1f;player.hasHit=true;++combo;comboTimer=1;maxCombo=std::max(maxCombo,combo);SpawnImpact(boss.pos,{120,240,120,255},true);hitstop=.12f;shake=.18f;if(boss.hp<=0)DefeatBoss();}}
void Stage4Game::UpdateCombat(float dt){if(comboTimer>0)comboTimer-=dt;else combo=0;player.Update(dt);if(player.state==PlayerState::Attack&&player.attackType==AttackType::Energy&&player.energyReleased){SpawnEnergy();player.energyReleased=false;}if(wave==0)SpawnWave(1);for(auto&e:enemies)if(e.active)e.Update(dt,player,&combatWorld);HandlePlayerHits();UpdateProjectiles(dt);HandleEnemyHits();combatWorld.Update(dt);combatWorld.ResolveHazards(player,enemies);defeated=(int)std::count_if(enemies.begin(),enemies.end(),[](const StreetEnemy&e){return e.IsDefeated();});bool cleared=true,found=false;for(auto&e:enemies){bool belongs=(wave==1&&e.position.x<1400)||(wave==2&&e.position.x>=1350&&e.position.x<2200)||(wave==3&&e.position.x>=2200&&e.position.x<3300)||(wave==4&&e.position.x>=3300&&e.position.x<4400);if(belongs){found=true;if(!e.IsDefeated())cleared=false;}}if(found&&cleared){arenaLocked=false;if(wave<4){if(player.position.x>(wave==1?1320:wave==2?2120:3220))SpawnWave(wave+1);}else if(player.position.x>4400)EnterBoss();}if(player.state==PlayerState::Defeat)flow=Flow::GameOver;}
void Stage4Game::UpdateBoss(float dt){if(boss.invuln>0)boss.invuln-=dt;if(flow==Flow::BossIntro){bannerTimer-=dt;kessler.Update(dt);if(IsKeyPressed(KEY_ENTER))kessler.Skip();player.position.x=std::min(player.position.x,boss.pos.x-270);if(bannerTimer<=0&&kessler.IsDone())flow=Flow::Boss;return;}if(boss.defeated)return;float ratio=(float)boss.hp/boss.maxHp;int ph=ratio<=.25f?4:ratio<=.5f?3:ratio<=.75f?2:1;if(ph!=boss.phase){boss.phase=ph;boss.attack=BossAttack::Overdrive;boss.elapsed=0;SpawnImpact(boss.pos,{110,255,140,255},true);shake=.28f;}boss.attackTimer-=dt;boss.elapsed+=dt;float dx=player.position.x-boss.pos.x;if(boss.attack==BossAttack::None&&boss.attackTimer<=0){int pick=GetRandomValue(0,boss.phase>=3?3:2);boss.attack=pick==0?BossAttack::Dash:pick==1?BossAttack::Shockwave:pick==2?BossAttack::ProjectileBurst:BossAttack::Overdrive;boss.elapsed=0;boss.attackTimer=boss.phase>=4?1.0f:boss.phase==3?1.25f:boss.phase==2?1.5f:1.85f;}if(boss.attack==BossAttack::None&&std::abs(dx)>210)boss.pos.x+=(dx>0?1:-1)*(boss.phase>=3?135.f:boss.phase==2?105.f:82.f)*dt;float tele=boss.attack==BossAttack::Dash?.4f:boss.attack==BossAttack::Shockwave?.6f:boss.attack==BossAttack::ProjectileBurst?.5f:.32f;CombatBox hit{};bool active=false;if(boss.attack!=BossAttack::None&&boss.elapsed>=tele){if(boss.attack==BossAttack::Dash){boss.pos.x+=(dx>0?1:-1)*640*dt;hit={boss.pos.x-110,boss.pos.y-130,220,135};active=boss.elapsed<=tele+.4f;}else if(boss.attack==BossAttack::Shockwave){hit={boss.pos.x-320,boss.pos.y-95,640,110};active=boss.elapsed<=tele+.22f;if(active&&boss.elapsed<tele+.03f)combatWorld.DoShake(0.22f);}else if(boss.attack==BossAttack::ProjectileBurst){if(boss.elapsed<tele+.05f){for(int i=-1;i<=1;++i)projectiles.push_back({{boss.pos.x,boss.pos.y-90+i*40.f,0},(dx>0?1.f:-1.f)*480.f,1.1f,boss.phase>=3?22:16,true,true});SpawnImpact({boss.pos.x,boss.pos.y-90},{120,255,140,255},true);}}else{hit={boss.pos.x-210,boss.pos.y-150,420,155};active=boss.elapsed<=tele+.34f;}}if(active&&hit.Intersects(player.GetHurtbox())&&player.state!=PlayerState::Hit){int dmg=boss.phase>=4?38:boss.phase==3?32:boss.phase==2?26:21;int before=player.hp;player.TakeDamage(dmg);damageTaken+=before-player.hp;combo=0;comboTimer=0;SpawnImpact(player.position,{125,240,120,255},true);hitstop=.11f;shake=.22f;}if(boss.attack!=BossAttack::None&&boss.elapsed>(boss.attack==BossAttack::Dash?1.0f:boss.attack==BossAttack::ProjectileBurst?.9f:.9f)){boss.attack=BossAttack::None;boss.elapsed=0;}boss.pos.x=std::clamp(boss.pos.x,4700.f,5450.f);boss.pos.y=std::clamp(boss.pos.y,kLaneMinY+25.f,kLaneMaxY);HandleBossHits();if(boss.hp<=0)DefeatBoss();}
void Stage4Game::DefeatBoss(){if(boss.defeated)return;boss.defeated=true;boss.attack=BossAttack::None;flow=Flow::Clear;SpawnImpact(boss.pos,{140,255,160,255},true);shake=.5f;}
void Stage4Game::UpdateParticles(float dt){for(auto&p:particles){p.life-=dt;p.pos.x+=p.vel.x*dt;p.pos.y+=p.vel.y*dt;p.vel.x*=.92f;p.vel.y*=.92f;}particles.erase(std::remove_if(particles.begin(),particles.end(),[](const Particle&p){return p.life<=0;}),particles.end());}
void Stage4Game::Update(float dt){dt=std::min(dt,.033f);if(IsKeyPressed(KEY_ESCAPE)){if(flow==Flow::Combat||flow==Flow::Boss)flow=Flow::Pause;else if(flow==Flow::Pause)flow=boss.defeated?Flow::Clear:Flow::Combat;}if(flow==Flow::Pause){if(IsKeyPressed(KEY_R))Init();return;}if(flow==Flow::GameOver){if(IsKeyPressed(KEY_R))Init();return;}if(flow==Flow::Clear){if(IsKeyPressed(KEY_ENTER)||IsKeyPressed(KEY_J))advanceRequested=true;return;}if(hitstop>0){hitstop-=dt;return;}shake=std::max(0.f,shake-dt);bannerTimer=std::max(0.f,bannerTimer-dt);UpdateParticles(dt);if(flow==Flow::Intro){if(IsKeyPressed(KEY_ENTER)||IsKeyPressed(KEY_J))flow=Flow::Combat;return;}stageTime+=dt;if(flow==Flow::Combat)UpdateCombat(dt);if(flow==Flow::BossIntro||flow==Flow::Boss)UpdateBoss(dt);float target=std::clamp(player.position.x,640.f,kStageEnd-640.f);cameraX+=(target-cameraX)*(1-std::pow(.001f,dt));}
void Stage4Game::DrawArenaLock() const{if(!arenaLocked)return;const int arenaEnd=(int)(wave==1?1400.f:wave==2?2200.f:wave==3?3300.f:4400.f);const int gate=arenaEnd-8;for(int i=-2;i<=2;++i){const int x=gate+i*18;DrawRectangle(x,420,6,220,{95,220,140,150});DrawLine(x,420,x+28,390,{140,255,180,110});}}
// DF-013.2: Titan-X Mejorado ahora se dibuja con el sprite real (segunda
// hoja de pose aportada por el usuario, mas dañada/con mas energia verde
// expuesta que la del prototipo de Stage3 — encaja con el canon de
// "evolucion descontrolada" de GAME_DESIGN.md). La pose sigue el
// BossAttack real (a diferencia del Titan-X de Stage3, este si mantiene
// el ataque activo en boss.attack durante toda su ventana).
//
// Tamaño: las hojas de referencia del usuario (comparativa Rayden / Titan-X
// / Titan-X XL) confirman que la forma final debe verse notoriamente mas
// grande que el prototipo — del orden de 2 a 3 veces la altura de Rayden.
// kTargetHeight se fija en consecuencia (170 para el prototipo en Stage3,
// ~300 aqui) y sigue creciendo un poco por fase para el efecto "furia".
void Stage4Game::DrawBoss() const{
    if(!boss.pos.x||boss.defeated)return;
    const float x=boss.pos.x,y=boss.pos.y;
    const bool flip=player.position.x>boss.pos.x;
    const char* pose="idle1";
    if(boss.attack==BossAttack::Dash)pose="dash";
    else if(boss.attack==BossAttack::Shockwave)pose="slam";
    else if(boss.attack==BossAttack::ProjectileBurst)pose=(boss.elapsed<.5f)?"charge_orb":"shoot_orb";
    else if(boss.attack==BossAttack::Overdrive)pose="rage_aura";
    else if(boss.invuln>.06f)pose="cannon_aim";
    else{
        const int cycle=((int)(boss.elapsed*1.4f))%4;
        pose=cycle==0?"idle1":cycle==1?"idle2":cycle==2?"idle3":"idle4";
    }
    Texture2D tex=AssetManager::Get().GetTexture(std::string("titanx_mejorado_")+pose);
    Color tint=boss.phase>=4?Color{255,215,190,255}:WHITE;
    if(boss.invuln>0)tint={255,190,190,255};
    const float targetHeight=225.f+(boss.phase-1)*8.f;
    DrawBossPose(tex,{x,y},targetHeight,flip,tint);
    if(boss.attack==BossAttack::Shockwave)DrawCircleLines((int)x,(int)y,90+std::sin((float)GetTime()*11)*10,{140,255,180,180});
}
void Stage4Game::DrawWorld() const{Camera2D c{};c.offset={640,360};c.target={cameraX,360};c.zoom=1;if(shake>0){c.target.x+=GetRandomValue(-100,100)*shake*8;c.target.y+=GetRandomValue(-100,100)*shake*5;}BeginMode2D(c);// DF-013.2: 4 escenarios propios (uno por oleada; el 4o es el nucleo del boss).
 const int sc=std::clamp(flow==Flow::Boss||flow==Flow::BossIntro?4:(wave<1?1:wave>4?4:wave),1,4);
 const Texture2D scenarioBg=AssetManager::Get().GetTexture(TextFormat("bg_s4_%d",sc));
 if(scenarioBg.id)DrawScenarioBackdrop(scenarioBg,cameraX,0.35f);
 else{Texture2D bg=AssetManager::Get().GetTexture("bg_zona_quimica");if(bg.id)DrawTexturePro(bg,{0,0,(float)bg.width,(float)bg.height},{cameraX-640,0,1280,720},{0,0},0,{255,255,255,235});else DrawRectangle((int)(cameraX-640),0,1280,720,{10,16,14,255});}DrawRectangle(0,635,(int)kStageEnd,100,{7,11,9,255});for(int x=0;x<(int)kStageEnd;x+=170){DrawRectangle(x,615,120,14,{30,45,35,255});DrawRectangle(x+25,650,80,5,{50,90,60,255});}for(int x=140;x<(int)kStageEnd;x+=460){DrawRectangle(x,260,14,300,{18,28,22,220});DrawCircle(x+7,255,6,{110,255,150,200});}DrawArenaLock();combatWorld.DrawGround();struct Item{float y;int id;};std::vector<Item>order{{player.position.y,-1}};for(size_t i=0;i<enemies.size();++i)if(enemies[i].active)order.push_back({enemies[i].position.y,(int)i});std::sort(order.begin(),order.end(),[](auto&a,auto&b){return a.y<b.y;});for(auto&i:order){if(i.id<0)player.Draw();else enemies[(size_t)i.id].Draw();}kessler.DrawWorld();DrawBoss();for(auto&p:projectiles){Vector2 s=p.pos.ToScreen();Color c=p.fromBoss?Color{120,255,150,255}:Color{50,220,255,255};DrawCircle((int)s.x,(int)s.y,20,Alpha(c,.35f));DrawCircle((int)s.x,(int)s.y,12,c);}for(auto&p:particles){Vector2 s=p.pos.ToScreen();float a=p.life/p.maxLife;DrawCircle((int)s.x,(int)s.y,p.size*a,Alpha(p.color,a));}combatWorld.DrawEffects();EndMode2D();}
void Stage4Game::DrawHUD() const{ui::PlayerVitals vitals{};vitals.hp=player.hp;vitals.maxHp=player.maxHp;vitals.shield=player.shield;vitals.maxShield=player.maxShield;vitals.sp=player.sp;vitals.maxSp=player.maxSp;vitals.rage=player.rage;vitals.maxRage=player.maxRage;vitals.isRageMode=player.isRageMode;vitals.combo=combo;vitals.title="RAYDEN CRUZ // KESSLER TOWER";vitals.x=16;vitals.y=14;vitals.width=500;vitals.panelHeight=132;ui::DrawPlayerVitals(vitals);DrawText(TextFormat("OLEADA %d/4",wave),1040,24,18,WHITE);if(flow==Flow::Boss||flow==Flow::BossIntro){DrawRectangle(280,18,720,48,{8,10,8,230});DrawText("TITAN-X MEJORADO // NUCLEO KESSLER",395,21,20,{150,255,180,255});DrawRectangle(350,50,580,12,{22,32,25,255});DrawRectangle(350,50,(int)(580.f*boss.hp/boss.maxHp),12,{100,235,140,255});DrawText(TextFormat("FASE %d/4",boss.phase),940,49,15,WHITE);}if(bannerTimer>0){const char*t=TextFormat("KESSLER TOWER // OLEADA %d",wave);DrawText(t,640-MeasureText(t,32)/2,190,32,{170,255,195,230});}}
void Stage4Game::DrawClear() const{DrawRectangle(0,0,1280,720,{6,10,8,245});DrawText("STAGE 4 CLEAR",420,100,58,{110,235,150,255});DrawText("KESSLER TOWER // NUCLEO EJECUTIVO",305,170,22,WHITE);DrawText(TextFormat("TIME        %6.1fs",stageTime),380,255,23,WHITE);DrawText(TextFormat("ENEMIES     %6d",defeated),380,295,23,WHITE);DrawText(TextFormat("DAMAGE      %6d",damageTaken),380,335,23,WHITE);DrawText(TextFormat("MAX COMBO   %6d",maxCombo),380,375,23,WHITE);DrawText("BOSS        TITAN-X MEJORADO",380,420,23,WHITE);DrawText("El nucleo de Kessler cae. Solo queda la camara del clon.",235,470,17,{200,220,205,235});DrawText("ENTER — STAGE 5: CAMARA DEL CLON",385,625,22,WHITE);}
void Stage4Game::Draw() const{DrawWorld();if(flow==Flow::Intro){DrawRectangle(0,0,1280,720,{5,10,8,150});DrawText("KESSLER TOWER // NUCLEO EJECUTIVO",300,285,36,{175,235,205,255});DrawText("Titan-X regreso. Ya no es un prototipo.",370,335,18,{200,220,205,230});DrawText("ENTER / J — START",490,375,22,WHITE);}if(flow==Flow::Combat||flow==Flow::BossIntro||flow==Flow::Boss)DrawHUD();kessler.DrawDialogue();if(flow==Flow::Pause){DrawHUD();DrawRectangle(0,0,1280,720,{0,0,0,160});DrawText("PAUSED",545,235,48,WHITE);DrawText("ESC — RESUME",500,330,22,WHITE);DrawText("R — RESTART",510,375,22,WHITE);}if(flow==Flow::GameOver){DrawHUD();DrawRectangle(0,0,1280,720,{0,0,0,180});DrawText("GAME OVER",440,250,60,{235,55,65,255});DrawText("R — RESTART",500,355,22,WHITE);}if(flow==Flow::Clear)DrawClear();}
}
